version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.15
      environment:
        ## this enables colors in the output
        TERM: xterm
jobs:
  build:
    <<: *defaults
    steps:
        - checkout
        - restore_cache:
            keys:
            - v3-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v3-deps-{{ .Branch }}-
            - v3-deps-
        - run:
            name: Install project dependencies
            command: | 
                yarn install
        - save_cache:
            key: v3-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            paths:
            - ~/.cache/yarn
        - persist_to_workspace:
            root: ~/
            paths:
            - .cache
            - project
            
  compile:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            name: Build Source Files
            command: |
                yarn run build

  test:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            name: Run Pact Test & Generate Report
            command: |
                yarn run pact-test   
        # - run:
        #     name: Publish Pact Contract to Broker
        #     command: |
        #         yarn run pact-publish
            
workflows:
  version: 2
  build-compile-test-publish:
    jobs:
      - build
      - compile:
          requires:
            - build
      - test:
          requires:
            - compile