version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.15
      environment:
        ## this enables colors in the output
        TERM: xterm
jobs:
  build:
    <<: *defaults
    steps:
        - checkout
        - restore_cache:
            keys:
            - v4-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v4-deps-{{ .Branch }}-
            - v4-deps-
        - run:
            name: Install project dependencies
            command: | 
                yarn install
        - save_cache:
            key: v4-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            paths:
            - ~/.cache/yarn
        - persist_to_workspace:
            root: ~/
            paths:
            - .cache
            - project
            
  compile:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            name: Build Source Files
            command: |
                yarn run build

  verify-test-publish:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            name: Validate Swagger spec
            command: |
                yarn run swagger-validate-spec 
        - run:
            name: Run Pact Test & Generate Report
            command: |
                yarn run pact-test   
        - run:
            name: Validate Pact contract against Swagger spec
            command: |
                yarn run swagger-validate-pact     
        - run:
            name: Publish pacts
            command: |
                yarn run pact-publish 
        - run:
            name: Tag Pacts
            command: |
                yarn run pact-tag

  provider-verify-node:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            shell: /bin/bash
            name: Provider verification with pact-node
            command: |
                yarn run pact-verify-provider-node

  provider-verify-js:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            shell: /bin/bash
            name: Provider verification with pact-js
            command: |
                yarn run pact-verify-provider-js

  provider-verify-https_broker-NODE:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            shell: /bin/bash
            name: Provider verification with pact-node https broker no ca
            command: |
                yarn run pact-verify-provider-https_broker-NODE

  provider-verify-https_broker-JS:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            shell: /bin/bash
            name: Provider verification with pact-node https broker no ca
            command: |
                yarn run pact-verify-provider-https_broker-JS

workflows:
  version: 2
  build-compile-test-publish:
    jobs:
      - build
      - compile:
          requires:
            - build
      - verify-test-publish:
          requires:
            - compile
      - provider-verify-node:
          requires:
            - verify-test-publish
      - provider-verify-js:
          requires:
            - verify-test-publish
      - provider-verify-https_broker-NODE:
          requires:
            - verify-test-publish
      - provider-verify-https_broker-JS:
          requires:
            - verify-test-publish